baseurl = "https://yanlong.me/"
languageCode = "zh-cn"
defaultContentLanguage = "zh-cn"
theme = "mainroad"
title = "ç«é¾™æœçš„åšå®¢"
paginate = 10
googleAnalytics = "G-RBZ1RJH1W8"
googleAdsense = "ca-pub-4136853851848129"

hasCJKLanguage = true

[menu]
  [[menu.footer]]
    url = "https://wujunze.com/"
    name = "å´é’§æ³½åšå®¢"
    target = "_blank"
  [[menu.footer]]
    url = "https://jicki.cn/"
    name = "å°ç‚’è‚‰"
    target = "_blank"
  [[menu.footer]]
    url = "https://yuerblog.cc/"
    name = "é±¼å„¿çš„åšå®¢"
    target = "_blank"
  [[menu.footer]]
    url = "http://www.is17.com/"
    name = "ä¾åä¸ƒ"
    target = "_blank"
    

[Author]
  name = "Yanlong"
  bio = "ç¨‹åºå‘˜ / Apache Committer / PECLæˆå‘˜"
  avatar = "img/avatar.jpeg"

[Params]
    subtitle = "ğŸ¥³No Code no Bugs"
    copyright = "yanlong.me"
    readmore = true
    authorbox = true
    post_meta = ["date", "categories"]
    dateformat = "2006-01-02"
    highlightColor = "#e22d30"

[Params.sidebar]
  home = "right"
  list = "right"
  single = true
  widgets = ["search", "recent", "categories", "taglist", "social", "languages"]

[Params.widgets.social]
  twitter = "YanlongHe"
  github = "heyanlong"
  email = "yanlong.hee@gmail.com"
